namespace GameJam
{
	internal class Program
	{
		public static Graphics g;

		static void Main(string[] _)
        {
			g = new(ConsoleColor.Gray, ConsoleColor.Black);
            
            Room rControl = new("Kontrolrummet", "Du træder ind i kontrolrummet på dit rumskib og bliver mødt af et futuristisk syn. Rummet er domineret af buede skærme og paneler med blinkende lys, der kaster et blødt skær over metaloverfladerne. Kontrolpanelet foran dig er fyldt med knapper, skærme og holografiske displays, der summer og summer med aktivitet.\n\nPå din venstre side ser du en række store skærme, der viser vitale oplysninger om skibets tilstand. Her kan du se hastighed, brændstofniveau, atmosfæretryk og energiforbrug. På højre side er en række kontrolpaneler, der styrer skibets forskellige systemer som navigation, kommunikation og våben.\n\nI midten af rummet er din kommandostol, polstret med blødt, sort læder og udstyret med en række justerbare knapper og skiver. Over stolen hænger en kuppellignende skærm, der giver dig en imponerende udsigt over det ydre rum gennem skibets panoramavindue.\n\nLangs væggene er der opbevaringsrum til udstyr og forsyninger, og små holografiske terminaler giver dig mulighed for at få adgang til skibets databaser og kommunikationssystemer.\n\nDet er et velorganiseret kontrolrum, der oser af moderne teknologi og muligheder. Du føler dig tryg og selvsikker i dette rum, vidende om at du har fuld kontrol over skibet og dets skæbne.");
			Room rLounge = new("Loungen", "Du træder ind i loungen på dit rumskib og bliver mødt af en afslappet atmosfære og en behagelig følelse af hjemlig komfort. Rummet er indrettet med bløde, polstrede møbler i neutrale farver, der indbyder til afslapning. De bløde, indirekte lyskilder skaber en hyggelig glød, der bryder den sterile æstetik fra kontrolrummet.\n\nMidt i rummet er der en rund sofa med dybe, komfortable puder, der omfavner dig, når du sætter dig. Ved siden af sofaen er der små borde med plads til drikkevarer og små snacks. En diskret musikanlæg fylder lokalet med en beroligende melodi.\n\nPå den ene væg er der et stort panoramavindue, der giver dig en betagende udsigt over det skiftende stjernebillede udenfor. Gardiner i lette stoffer kan trækkes for, hvis du foretrækker en mere intim atmosfære.\n\nPå den modsatte væg findes en lille bar med et udvalg af drikkevarer og en automatisk kaffemaskine. Over baren hænger billeder af fjerne galakser og stjernesystemer, der minder dig om din placering i universet.\n\nRummet er fyldt med blide vibrationer fra skibets motorer, der skaber en beroligende akustik. Det er et sted, hvor man kan slappe af, fordøje indtryk fra rummet og finde en stund med ro og eftertænksomhed. Det er klart, at rummet er designet til at give besætningen mulighed for at finde hvile og komme sig, så de kan fortsætte deres opdagelsesrejse med frisk energi.");
			Room rScience = new("Dit sovekammer / laboratoriet", "Du træder ind i dit sovekammer, der er lige så enestående som det er praktisk. Rummet er lidt mindre end de andre på skibet, men det er fyldt med avanceret teknologi og multifunktionelt udstyr. På den ene væg er der en kompliceret række af laboratorieudstyr, inklusive prøveglas, mikroskoper og elektroniske instrumenter, der er omhyggeligt organiseret.\n\nPå den modsatte væg er der en behagelig, foldbar seng med bløde, højteknologiske materialer, der former sig efter din krop og giver dig den bedst mulige nattesøvn. Over sengen er der et lille kontrolpanel, hvor du kan indstille temperatur, belysning og lyde for at skabe den perfekte atmosfære til hvile eller arbejde.\n\nVed siden af sengen er der et lille arbejdsbord med en indbygget computerterminal og en lille skærm, der giver dig adgang til skibets databaser og laboratorieinformation. Hylder fyldt med bøger, notater og videnskabelig udstyr omgiver arbejdsbordet og giver dig alt, hvad du har brug for til dine forskningsprojekter.\n\nRummet er belyst med blødt, dæmpet lys, der kan justeres efter behov. Gulvet er dækket af et behageligt og isolerende materiale, der giver en komfortabel følelse under fødderne.\n\nDet er et rum, der udstråler både funktionalitet og komfort, og det er tydeligt, at det er blevet designet med omhu og opmærksomhed på detaljer for at imødekomme dine behov som forsker og hvilested for besætningsmedlemmet.");
			Room rCaptain = new("Kaptajnens sovekammer", "Du træder ind i kaptajnens sovekammer, og det første, der slår dig, er en følelse af udsøgt elegance kombineret med avanceret teknologi. Rummet er større end de andre på skibet og er indrettet med en subtil luksus.\n\nPå den ene væg er der en række avancerede kontrolpaneler, der styrer skibets vitale systemer. Herfra kan kaptajnen overvåge alt fra energiforbrug til skjoldstyrke og navigationsparametre. Holografiske displays skaber en visuel symfoni af information.\n\nPå den modsatte væg er der en imponerende seng i kongelig størrelse med silkebetræk og puder fyldt med det blødeste materiale, der findes i galaksen. Over sengen er der en integreret hovedgavl med indbyggede læselamper og personlige underholdningssystemer.\n\nVed siden af sengen er der et elegant arbejdsbord af ædeltræ, hvor kaptajnen kan udføre vigtige opgaver og tage beslutninger. Et antikt kompas og en række personlige genstande, herunder fotografier fra tidligere opdagelser, giver rummet en personlig præg.\n\nEt hjørne af rummet er dedikeret til laboratoriearbejde. Her finder man avancerede apparater, testrør og forskningsudstyr, der er omhyggeligt organiseret og klar til brug.\n\nBelysningen kan justeres fra dæmpet til skarpt, afhængigt af kaptajnens præferencer. Gulvet er dækket af et eksklusivt gulvtæppe, der føles blødt under fødderne.\n\nAlt i alt udstråler kaptajnens sovekammer både magt, stil og effektivitet. Det er et rum, der er skræddersyet til at imødekomme behovene og smagen hos en leder og opdagelsesrejsende som kaptajnen.");
			Room[] rooms = { rControl, rLounge, rScience, rCaptain };

            rControl.AdjecentRooms = new Room[] { null, rLounge, rCaptain, null };
			rLounge.AdjecentRooms = new Room[] { rControl, null, rCaptain, rScience };
			rScience.AdjecentRooms = new Room[] { null, null, rLounge, null };
			rCaptain.AdjecentRooms = new Room[] { rControl, null, null, rLounge };

            Crew cKarl = new("Karl", "Gamer", ConsoleColor.Yellow, rControl);
            Crew cIb = new("Ib", "Gamer", ConsoleColor.Magenta, rControl);
            Crew cBob = new("Bob", "Gamer", ConsoleColor.Cyan, rControl);

            NavSystem nav = new(rooms);
			nav.Start(new(rLounge));
		}
	}
}